# Your Name or Company
title: Will Bolton

# Description of your website. This is used for social sharing.
description:  Will Bolton's personal website.

# A brief blurb about yourself
content: Hi, my name is Will. I am currently undertaking my PhD as part of the AI4Health CDT at Imperial College London. My work focuses on creating intelligent clinical decision support systems to improve the diagnosis and management of infectious diseases in multimorbid patients. Previously I obtained my Masters in Bioscience Enterprise at the University of Cambridge and gained professional experience at a global healthcare consultancy firm. I have a passion for entrepreneurship and am highly interested in start ups and how applying innovative technology can create solutions to real world problems. Please feel free to reach out, I look forward to connecting!

# Add your social links
social:
  #- platform: github
  #  url: https://github.com/WilliamBolton
  #- platform: facebook
  #  url: https://facebook.com/brianmaierjr
  #- platform: twitter
  #  url: https://twitter.com/brianmaierjr
  - platform: email
    url: mailto:william.bolton15@imperial.ac.uk
  - platform: linkedin
    url: https://www.linkedin.com/in/william-bolton
  - platform: github
    url: https://github.com/WilliamBolton

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: 0C00098E-661B-4D78-9D9A-E4FD1FD1912E_1_105_c.jpeg
#google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
